/* soapClient.cpp
   Generated by gSOAP 2.8.17r from fun.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.17r 2014-05-14 09:44:54 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__queryObjectOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string _xtlb, std::string _jkxlh, std::string _jkid, std::string _UTF8XmlDoc, std::string &_queryObjectOutReturn)
{	struct ns1__queryObjectOut soap_tmp_ns1__queryObjectOut;
	struct ns1__queryObjectOutResponse *soap_tmp_ns1__queryObjectOutResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.172.134.9:9080/trffweb/services/TmriOutAccess";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__queryObjectOut._xtlb = _xtlb;
	soap_tmp_ns1__queryObjectOut._jkxlh = _jkxlh;
	soap_tmp_ns1__queryObjectOut._jkid = _jkid;
	soap_tmp_ns1__queryObjectOut._UTF8XmlDoc = _UTF8XmlDoc;
	soap_serializeheader(soap);
	soap_serialize_ns1__queryObjectOut(soap, &soap_tmp_ns1__queryObjectOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__queryObjectOut(soap, &soap_tmp_ns1__queryObjectOut, "ns1:queryObjectOut", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__queryObjectOut(soap, &soap_tmp_ns1__queryObjectOut, "ns1:queryObjectOut", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_queryObjectOutReturn)
		return soap_closesock(soap);
	soap_default_std__string(soap, &_queryObjectOutReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__queryObjectOutResponse = soap_get_ns1__queryObjectOutResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__queryObjectOutResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	_queryObjectOutReturn = soap_tmp_ns1__queryObjectOutResponse->_queryObjectOutReturn;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__writeObjectOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string _xtlb, std::string _jkxlh, std::string _jkid, std::string _UTF8XmlDoc, std::string &_writeObjectOutReturn)
{	struct ns1__writeObjectOut soap_tmp_ns1__writeObjectOut;
	struct ns1__writeObjectOutResponse *soap_tmp_ns1__writeObjectOutResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://10.172.134.9:9080/trffweb/services/TmriOutAccess";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/";
	soap_tmp_ns1__writeObjectOut._xtlb = _xtlb;
	soap_tmp_ns1__writeObjectOut._jkxlh = _jkxlh;
	soap_tmp_ns1__writeObjectOut._jkid = _jkid;
	soap_tmp_ns1__writeObjectOut._UTF8XmlDoc = _UTF8XmlDoc;
	soap_serializeheader(soap);
	soap_serialize_ns1__writeObjectOut(soap, &soap_tmp_ns1__writeObjectOut);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns1__writeObjectOut(soap, &soap_tmp_ns1__writeObjectOut, "ns1:writeObjectOut", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns1__writeObjectOut(soap, &soap_tmp_ns1__writeObjectOut, "ns1:writeObjectOut", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&_writeObjectOutReturn)
		return soap_closesock(soap);
	soap_default_std__string(soap, &_writeObjectOutReturn);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns1__writeObjectOutResponse = soap_get_ns1__writeObjectOutResponse(soap, NULL, "", "");
	if (!soap_tmp_ns1__writeObjectOutResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	_writeObjectOutReturn = soap_tmp_ns1__writeObjectOutResponse->_writeObjectOutReturn;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
