/* soapTmriOutAccessSoapBindingProxy.h
   Generated by gSOAP 2.8.7 from fun.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapTmriOutAccessSoapBindingProxy_H
#define soapTmriOutAccessSoapBindingProxy_H
#include "soapH.h"
class TmriOutAccessSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'TmriOutAccessSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	TmriOutAccessSoapBinding()
	{ soap = soap_new(); endpoint = "http://10.172.134.9:9080/trffweb/services/TmriOutAccess"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://endpoint.axis.framework.tmri.com", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~TmriOutAccessSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'queryObjectOut' of service 'TmriOutAccessSoapBinding' and return error code (or SOAP_OK)
	virtual int ns1__queryObjectOut(std::string _xtlb, std::string _jkxlh, std::string _jkid, std::string _UTF8XmlDoc, std::string &_queryObjectOutReturn) { return soap ? soap_call_ns1__queryObjectOut(soap, endpoint, NULL, _xtlb, _jkxlh, _jkid, _UTF8XmlDoc, _queryObjectOutReturn) : SOAP_EOM; };
	/// Invoke 'writeObjectOut' of service 'TmriOutAccessSoapBinding' and return error code (or SOAP_OK)
	virtual int ns1__writeObjectOut(std::string _xtlb, std::string _jkxlh, std::string _jkid, std::string _UTF8XmlDoc, std::string &_writeObjectOutReturn) { return soap ? soap_call_ns1__writeObjectOut(soap, endpoint, NULL, _xtlb, _jkxlh, _jkid, _UTF8XmlDoc, _writeObjectOutReturn) : SOAP_EOM; };
};
#endif
