/* soapStub.h
   Generated by gSOAP 2.8.17r from fun.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#include "stdsoap2.h"
#if GSOAP_VERSION != 20817
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns1__queryObjectOutResponse
#define SOAP_TYPE_ns1__queryObjectOutResponse (11)
/* ns1:queryObjectOutResponse */
struct ns1__queryObjectOutResponse
{
public:
	std::string _queryObjectOutReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
public:
	int soap_type() const { return 11; } /* = unique type id SOAP_TYPE_ns1__queryObjectOutResponse */
};
#endif

#ifndef SOAP_TYPE_ns1__queryObjectOut
#define SOAP_TYPE_ns1__queryObjectOut (12)
/* ns1:queryObjectOut */
struct ns1__queryObjectOut
{
public:
	std::string _xtlb;	/* required element of type xsd:string */
	std::string _jkxlh;	/* required element of type xsd:string */
	std::string _jkid;	/* required element of type xsd:string */
	std::string _UTF8XmlDoc;	/* required element of type xsd:string */
public:
	int soap_type() const { return 12; } /* = unique type id SOAP_TYPE_ns1__queryObjectOut */
};
#endif

#ifndef SOAP_TYPE_ns1__writeObjectOutResponse
#define SOAP_TYPE_ns1__writeObjectOutResponse (14)
/* ns1:writeObjectOutResponse */
struct ns1__writeObjectOutResponse
{
public:
	std::string _writeObjectOutReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
public:
	int soap_type() const { return 14; } /* = unique type id SOAP_TYPE_ns1__writeObjectOutResponse */
};
#endif

#ifndef SOAP_TYPE_ns1__writeObjectOut
#define SOAP_TYPE_ns1__writeObjectOut (15)
/* ns1:writeObjectOut */
struct ns1__writeObjectOut
{
public:
	std::string _xtlb;	/* required element of type xsd:string */
	std::string _jkxlh;	/* required element of type xsd:string */
	std::string _jkid;	/* required element of type xsd:string */
	std::string _UTF8XmlDoc;	/* required element of type xsd:string */
public:
	int soap_type() const { return 15; } /* = unique type id SOAP_TYPE_ns1__writeObjectOut */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (16)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 16; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (17)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 17; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (19)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 19; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (22)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 22; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (23)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 23; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__queryObjectOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string _xtlb, std::string _jkxlh, std::string _jkid, std::string _UTF8XmlDoc, std::string &_queryObjectOutReturn);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns1__writeObjectOut(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string _xtlb, std::string _jkxlh, std::string _jkid, std::string _UTF8XmlDoc, std::string &_writeObjectOutReturn);

#endif

/* End of soapStub.h */
